fix publish

diff --git a/.github/workflows/publish.yml b/.github/workflows/publish.yml
--- a/.github/workflows/publish.yml
+++ b/.github/workflows/publish.yml
@@ -105,27 +105,26 @@ jobs:
     - name: Check tag matches version set
       working-directory: ${{ env.WORKSPACE }}
       run: |
-        BUILD_VER=$(grep '__version__' oasislmf/__init__.py | awk -F"'" '{print $2}')
-        RELEASE_VER=$(echo ${{ env.RELEASE_TAG }} | cut -c2-)
-        [[ "$RELEASE_VER" = "$BUILD_VER" ]] && ERROR_CODE=0 || ERROR_CODE=1
-        if [[ "$ERROR_CODE" == 1 ]]; then
-            echo "PACKAGE_VER: $BUILD_VER stored in 'oasislmf/__init__.py' dosn't match RELEASE_TAG: $RELEASE_VER" && exit $ERROR_CODE
-        fi
+       BUILD_VER=$(grep '__version__' oasislmf/__init__.py | awk -F"'" '{print $2}')
+       RELEASE_VER=$(echo ${{ env.RELEASE_TAG }} | cut -c2-)
+       [[ "$RELEASE_VER" = "$BUILD_VER" ]] && ERROR_CODE=0 || ERROR_CODE=1
+       if [[ "$ERROR_CODE" == 1 ]]; then
+           echo "PACKAGE_VER: $BUILD_VER stored in 'oasislmf/__init__.py' dosn't match RELEASE_TAG: $RELEASE_VER" && exit $ERROR_CODE
+       fi
 
-     - name: Test package names
-       run: |
-         #ERROR_CODE=0
-         #SRC_VER=$(echo ${{ needs.build.outputs.src_pkg_filename }} | grep -oP "(\d*)\.(\d*)\.(\d*)rc(\d*)|(\d*)\.(\d*)\.(\d*)")
-         #BIN_VER=$(echo ${{ needs.build.outputs.linux_pkg_filename }} | grep -oP "(\d*)\.(\d*)\.(\d*)rc(\d*)|(\d*)\.(\d*)\.(\d*)")
-         #TAG=${{ env.RELEASE_TAG }}
-         #[[ "$TAG" = "$SRC_VER" ]] || ERROR_CODE=1
-         #[[ "$TAG" = "$BIN_VER" ]] || ERROR_CODE=1
-         #if [[ "$ERROR_CODE" == 1 ]]; then
-         #    echo "Package names don't match release tag."
-         #    echo "  RELEASE_TAG: $TAG"
-         #    echo "  PACKAGES: ${{ needs.build.outputs.src_pkg_filename }}, ${{ needs.build.outputs.linux_pkg_filename }}"
-         #    exit $ERROR_CODE
-         #fi
+    - name: Test package names
+      run: |
+        ERROR_CODE=0
+        SRC_VER=$(echo ${{ needs.build.outputs.src_pkg_filename }} | grep -oP "(\d*)\.(\d*)\.(\d*)rc(\d*)|(\d*)\.(\d*)\.(\d*)")
+        BIN_VER=$(echo ${{ needs.build.outputs.linux_pkg_filename }} | grep -oP "(\d*)\.(\d*)\.(\d*)rc(\d*)|(\d*)\.(\d*)\.(\d*)")
+        [[ "${{ env.RELEASE_TAG }}" = "$SRC_VER" ]] || ERROR_CODE=1
+        [[ "${{ env.RELEASE_TAG }}" = "$BIN_VER" ]] || ERROR_CODE=1
+        if [[ "$ERROR_CODE" == 1 ]]; then
+            echo "Package names don't match release tag."
+            echo "  RELEASE_TAG: ${{ env.RELEASE_TAG }}"
+            echo "  PACKAGES: ${{ needs.build.outputs.src_pkg_filename }}, ${{ needs.build.outputs.linux_pkg_filename }}"
+            exit $ERROR_CODE
+        fi
 
  # --- Setup Changelog builder script --- #
     - name: Setup github user
